export const routes = Object.freeze({
  home: '/',
  login: '/login',
  acceptInvitation: '/accept-invitation',
  selectCompany: '/select-company',
  companies: '/companies',
  companyAccess: '/company-access',
  branches: '/branches',
  warehouseCategories: '/warehouse-categories',
  warehouses: '/warehouses',
  locations: '/locations',
  suppliers: '/suppliers',
  users: '/users',
  roles: '/roles',
  permissions: '/permissions',
  sessions: '/sessions',
  audit: '/audit',
  entityChanges: '/audit/entity-changes',
  profile: '/profile',
  changePassword: '/change-password',
  preferences: '/preferences',
  unauthorized: '/unauthorized',
  notFound: '/not-found',
});
