import { routes } from '@/app/routes.js';
import { environment } from '@/config/environment.js';
import { permissions } from '@/config/permissions.js';

export const navigationItems = Object.freeze([
  Object.freeze({
    key: 'companies',
    label: 'Empresas',
    path: routes.companies,
    icon: 'companies',
    permission: permissions.companies.read,
  }),
  Object.freeze({
    key: 'company-access',
    label: 'Acceso de empresa',
    path: routes.companyAccess,
    icon: 'roles',
    permission: permissions.companyMembers.read,
  }),
  Object.freeze({
    key: 'branches',
    label: 'Sucursales',
    path: routes.branches,
    icon: 'branches',
    permission: permissions.branches.read,
  }),
  Object.freeze({
    key: 'warehouse-categories',
    label: 'Categorías de almacén',
    path: routes.warehouseCategories,
    icon: 'warehouseCategories',
    permission: permissions.warehouseCategories.read,
  }),
  Object.freeze({
    key: 'warehouses',
    label: 'Almacenes',
    path: routes.warehouses,
    icon: 'warehouses',
    permission: permissions.warehouses.read,
  }),
  Object.freeze({
    key: 'locations',
    label: 'Ubicaciones',
    path: routes.locations,
    icon: 'locations',
    permission: permissions.locations.read,
  }),
  Object.freeze({
    key: 'suppliers',
    label: 'Proveedores',
    path: routes.suppliers,
    icon: 'suppliers',
    permission: permissions.suppliers.read,
  }),
  Object.freeze({
    key: 'brands',
    label: 'Marcas',
    path: routes.brands,
    icon: 'brands',
    permission: permissions.brands.read,
  }),
  Object.freeze({
    key: 'product-categories',
    label: 'Categorías de productos',
    path: routes.productCategories,
    icon: 'productCategories',
    permission: permissions.productCategories.read,
  }),
  Object.freeze({
    key: 'product-units',
    label: 'Unidades comerciales',
    path: routes.productUnits,
    icon: 'productUnits',
    permission: permissions.productUnits.read,
  }),
  Object.freeze({
    key: 'products',
    label: 'Productos',
    path: routes.products,
    icon: 'products',
    permission: permissions.products.read,
  }),
  Object.freeze({
    key: 'purchase-requests',
    label: 'Solicitudes de compra',
    path: routes.purchaseRequests,
    icon: 'purchaseRequests',
    permission: permissions.purchaseRequests.read,
  }),
  Object.freeze({
    key: 'expense-types',
    label: 'Tipos de gasto',
    path: routes.expenseTypes,
    icon: 'expenseTypes',
    permission: permissions.expenseTypes.read,
  }),
  Object.freeze({
    key: 'purchase-quotations',
    label: 'Cotizaciones de compra',
    path: routes.purchaseQuotations,
    icon: 'purchaseQuotations',
    permission: permissions.purchaseQuotations.read,
  }),
  Object.freeze({
    key: 'purchase-quotation-comparison',
    label: 'Comparación de cotizaciones',
    path: routes.purchaseQuotationComparison,
    icon: 'quotationComparison',
    permission: permissions.purchaseQuotations.read,
  }),
  Object.freeze({
    key: 'purchase-orders',
    label: 'Órdenes de compra',
    path: routes.purchaseOrders,
    icon: 'purchaseOrders',
    permission: permissions.purchaseOrders.read,
  }),
  Object.freeze({
    key: 'purchases',
    label: 'Recepciones de compra',
    path: routes.purchases,
    icon: 'purchases',
    permission: permissions.purchases.read,
  }),
  Object.freeze({
    key: 'home',
    label: 'Inicio',
    path: routes.home,
    icon: 'dashboard',
  }),
  Object.freeze({
    key: 'users',
    label: 'Usuarios',
    path: routes.users,
    icon: 'users',
    permission: permissions.users.read,
  }),
  Object.freeze({
    key: 'roles',
    label: 'Roles',
    path: routes.roles,
    icon: 'roles',
    permission: permissions.roles.read,
  }),
  Object.freeze({
    key: 'permissions',
    label: 'Permisos',
    path: routes.permissions,
    icon: 'permissions',
    permission: permissions.permissions.read,
  }),
  Object.freeze({
    key: 'sessions',
    label: 'Sesiones',
    path: routes.sessions,
    icon: 'sessions',
    permission: permissions.sessions.read,
  }),
  Object.freeze({
    key: 'audit',
    label: 'Auditoría',
    path: routes.audit,
    icon: 'history',
    permission: permissions.audit.read,
    enabled: environment.enableAuditModule,
  }),
  Object.freeze({
    key: 'entity-changes',
    label: 'Historial de cambios',
    path: routes.entityChanges,
    icon: 'audit',
    permission: permissions.audit.read,
    enabled: environment.enableAuditModule,
  }),
]);
