import { routes } from '@/app/routes.js';
import { environment } from '@/config/environment.js';
import { permissions } from '@/config/permissions.js';

export const navigationItems = Object.freeze([
  Object.freeze({
    key: 'companies',
    label: 'Empresas',
    path: routes.companies,
    icon: 'home',
    permission: permissions.companies.read,
  }),
  Object.freeze({
    key: 'company-access',
    label: 'Acceso de empresa',
    path: routes.companyAccess,
    icon: 'roles',
    permission: permissions.companyMembers.read,
  }),
  Object.freeze({
    key: 'branches',
    label: 'Sucursales',
    path: routes.branches,
    icon: 'home',
    permission: permissions.branches.read,
  }),
  Object.freeze({
    key: 'warehouse-categories',
    label: 'Categorías de almacén',
    path: routes.warehouseCategories,
    icon: 'home',
    permission: permissions.warehouseCategories.read,
  }),
  Object.freeze({
    key: 'warehouses',
    label: 'Almacenes',
    path: routes.warehouses,
    icon: 'home',
    permission: permissions.warehouses.read,
  }),
  Object.freeze({
    key: 'locations',
    label: 'Ubicaciones',
    path: routes.locations,
    icon: 'home',
    permission: permissions.locations.read,
  }),
  Object.freeze({
    key: 'suppliers',
    label: 'Proveedores',
    path: routes.suppliers,
    icon: 'users',
    permission: permissions.suppliers.read,
  }),
  Object.freeze({
    key: 'brands',
    label: 'Marcas',
    path: routes.brands,
    icon: 'home',
    permission: permissions.brands.read,
  }),
  Object.freeze({
    key: 'product-categories',
    label: 'Categorías de productos',
    path: routes.productCategories,
    icon: 'home',
    permission: permissions.productCategories.read,
  }),
  Object.freeze({
    key: 'product-units',
    label: 'Unidades comerciales',
    path: routes.productUnits,
    icon: 'home',
    permission: permissions.productUnits.read,
  }),
  Object.freeze({
    key: 'products',
    label: 'Productos',
    path: routes.products,
    icon: 'home',
    permission: permissions.products.read,
  }),
  Object.freeze({
    key: 'home',
    label: 'Inicio',
    path: routes.home,
    icon: 'home',
  }),
  Object.freeze({
    key: 'users',
    label: 'Usuarios',
    path: routes.users,
    icon: 'users',
    permission: permissions.users.read,
  }),
  Object.freeze({
    key: 'roles',
    label: 'Roles',
    path: routes.roles,
    icon: 'roles',
    permission: permissions.roles.read,
  }),
  Object.freeze({
    key: 'permissions',
    label: 'Permisos',
    path: routes.permissions,
    icon: 'permissions',
    permission: permissions.permissions.read,
  }),
  Object.freeze({
    key: 'sessions',
    label: 'Sesiones',
    path: routes.sessions,
    icon: 'sessions',
    permission: permissions.sessions.read,
  }),
  Object.freeze({
    key: 'audit',
    label: 'Auditoría',
    path: routes.audit,
    icon: 'audit',
    permission: permissions.audit.read,
    enabled: environment.enableAuditModule,
  }),
  Object.freeze({
    key: 'entity-changes',
    label: 'Historial de cambios',
    path: routes.entityChanges,
    icon: 'audit',
    permission: permissions.audit.read,
    enabled: environment.enableAuditModule,
  }),
]);
